version: "3.9"

services:
  db:
    image: postgres:15
    container_name: rental_db
    restart: always
    environment:
      POSTGRES_DB: rental_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: rental_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/rental_db
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: admin123
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: rental_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  pgdata:
